// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MdiBriefcase: typeof import('virtual:vite-icons/mdi/briefcase')['default']
    MdiBriefcaseVariant: typeof import('virtual:vite-icons/mdi/briefcase-variant')['default']
    MdiBrightness4: typeof import('virtual:vite-icons/mdi/brightness4')['default']
    MdiBrightness7: typeof import('virtual:vite-icons/mdi/brightness7')['default']
    MdiBrightnessAuto: typeof import('virtual:vite-icons/mdi/brightness-auto')['default']
    MdiCloud: typeof import('virtual:vite-icons/mdi/cloud')['default']
    MdiConnection: typeof import('virtual:vite-icons/mdi/connection')['default']
    MdiDatabase: typeof import('virtual:vite-icons/mdi/database')['default']
    MdiGithub: typeof import('virtual:vite-icons/mdi/github')['default']
    MdiInformation: typeof import('virtual:vite-icons/mdi/information')['default']
    MdiSearch: typeof import('virtual:vite-icons/mdi/search')['default']
    MdiSync: typeof import('virtual:vite-icons/mdi/sync')['default']
    PopupGist: typeof import('./src/components/PopupGist.vue')['default']
    PopupInfo: typeof import('./src/components/PopupInfo.vue')['default']
    QueryBox: typeof import('./src/components/QueryBox.vue')['default']
  }
}

export { }
